add_newline = false

[directory]
fish_style_pwd_dir_length = 1

[nodejs]
format = "via [⬢ $version](bold green) "

[c]
commands = [ [ 'clang', '--version' ], [ 'cc', '--version' ], [ 'gcc', '--version' ] ]
