theme = "gruvbox"

[editor]
line-number = "relative"
scrolloff = 8
idle-timeout = 0
cursorline = true
auto-format = false
auto-completion = false
rulers = [80]
mouse = false
auto-pairs = false
true-color = true

[editor.lsp]
display-messages = true
display-signature-help-docs = false

[editor.file-picker]
hidden = false

[editor.whitespace.render]
render = false

[editor.indent-guides]
render = true
